---
plugins: []
extends:
  - "eslint:recommended"
  - "airbnb-base"
env:
  browser: true
  node: false
  commonjs: false
  shared-node-browser: true
  es6: true
  worker: false
  amd: false
  mocha: false
  jasmine: false
  jest: false
  jquery: false
  mongo: false
  serviceworker: false
  webextensions: false
parser: "esprima"
parserOptions:
  ecmaVersion: 9
  sourceType: "script"
  ecmaFeatures:
    globalReturn: false
    impliedStrict: true
    jsx: false
rules:
  comma-dangle:
    - "error"
    - "only-multiline"
  consistent-return:
    - "error"
    - treatUndefinedAsUnspecified: false
  indent:
    - "error"
    - 2
    - SwitchCase: 0
      VariableDeclarator:
        var: 2
        let: 2
        const: 3
  linebreak-style:
    - "error"
    - "unix"
  max-len:
    - "error"
    - code: 110
      tabWidth: 2
      ignoreComments: true
      ignoreTrailingComments: false
      ignoreUrls: true
      ignoreStrings: false
      ignoreTemplateLiterals: false
      ignoreRegExpLiterals: true
  no-bitwise: "off"
  no-continue: "off"
  no-labels:
    - "error"
    - allowLoop: true
      allowSwitch: false
  no-param-reassign:
    - "off"
    - props: false
  no-plusplus:
    - "off"
    - allowForLoopAfterthoughts: true
  no-prototype-builtins: "off"
  no-restricted-syntax:
    - "error"
    - "WithStatement"
  padded-blocks:
    - "off"
    - blocks: always
      classes: always
      switches: never
  prefer-destructuring:
    - "error"
    - VariableDeclarator:
        array: false
        object: true
      AssignmentExpression:
        array: false
        object: true
    - enforceForRenamedProperties: false
  prefer-rest-params: "off"
  quotes:
    - "error"
    - "single"
  quote-props:
    - "error"
    - "consistent-as-needed"
    - keywords: true
      unnecessary: true
      numbers: false
  radix:
    - "error"
    - "as-needed"
  semi:
    - "error"
    - "always"
  strict:
    - "off"
    - "safe"
